file_format: "1"
id: totem_custom 
name: Totem 
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - totem_custom_left 
  - totem_custom_right
  - totem_custom_dongle