file_format: "1"
id: totem
name: TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - totem_dongle_left
  - totem_dongle_right
  - totem_dongle_central