file_format: "1"
id: peppakbd
name: peppakbd
type: shield
url: https://github.com/peppapighs/peppakbd
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - peppakbd_left
  - peppakbd_right
  - peppakbd_dongle